# Javascript Node CircleCI 2.0 configuration file
version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test
      - run: yarn build
